### ISSUE TITLE
List of commits to potentially port to 1.4

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#1163]
Oh boy.

Only some of these may not be needed.

In case of ExampleMod commits, do the changes to ExampleMod/Old entries. If they weren't deleted.

- [x] ecc983f - `Show tModLoader version everywhere in server menus.`
- [x] f913a7e - `Fix semicolon issue with mod generator postbuild command on linux/mac`
- [x] a246097 - `Fix #890`
- [x] 8ffbd6d - `Utils.OpenFolder, Fix #927 Fix #909 , savehere.txt fallback option`
- [x] 475faad - `Quick bandaid for #911`
- [x] 266bf53 - `v0.11.7.2 release`
- [x] 5db4c2a - `Avoid environment variable conflict`
- [x] f42c155 - `Fix content dir check for Mac`
- [x] ccdb09b - `Small fix, use ModLoader.Engine.Steam.TerrariaAppId_t`
- [x] 55996b8 - `Fix setup tool still mentioning merged source`
- [x] 03067a2 - `Refactor GoGVerifier &amp; update hashes`
- [x] 45a2baf - `Fix some mistakes in previous commit`
- [x] d0ea352 - `Turn ModRecipe into builder pattern`
- [x] 1296e29 - `Fix LogArchiver.DeleteOldArchives() not working with old logs`
- [x] 4bc2329 - `Fix a RandomUpdate issue (Surface updates)`
- [x] a256f9e - `Use lazy system for loading assembly references when building.`
- [x] de821c2 - `use portable pdb writer when building mods with includePDB on Mono.`
- [x] 459cf2b - `Add null check in MdbManager.TryResolveLocation incase MdbReader.Read fails. Fixes #929`
~~615230d - `Fix #936`~~
- [x] bd7aa52 - `Update ExampleLaserWeapon.cs`
- [x] 4c6f6b6 - `Add PaintID.cs (#938) ` --- (I think this one is already in tml)
- [x] bdcd2e9 - `make MessageBoxShow overload that optionally generates tips (#871)`
- [x] 0ef46ef - `Example Last Prism (#803)`
- [x] b06687a - `#850`
- [x] feaa038 - `Added a menu for when world gen crashes. (#825)`
- [x] ff5a774 - `Documentation fix`
~~54cacac - `Revert changes of &quot;Turn ModRecipe into builder pattern&quot;`~~
- [x] da78441 - `Update UIModConfig.cs`
- [x] 56bbe30 - `Fix #934`
- [x] c55545b - `Forgot this`
- [x] 9f62c59 - `New hashes for easier gog install`
- [x] 4b1c029 - `Steam Cloud Quota log message`
- [x] 73a7d36 - `showMemoryEstimates default to true.`
- [x] df9b1ee - `v0.11.7.3 release`
~~8ee2966 - `v0.11.7.4 release, fix npc spawning issue from 0.11.7.3 update`~~
- [x] c938604 - `Updated Spanish localization (#946)`
- [x] f416f26 - `Update Terraria.Localization.Content.zh-Hans.tModLoader.json (#944)`
- [x] c9c1725 - `Restore modded banner tooltip display`
- [x] 552d835 - `Update hashes for 1.4.0.5`
- [ ] 3029e6c - `Merge remote-tracking branch &#39;origin/master&#39;`
- [x] baa1e52 - `Fix LaunchFromSteam typo`
- [x] 7914b11 - `Update PULL_REQUEST_TEMPLATE.md`
- [x] a227d27 - `Update PULL_REQUEST_TEMPLATE.md`
- [x] 4356f94 - `Update zh-Hans.tModLoader.json (#954)`
- [x] 57de6f9 - `Fix #969`
~~1852e2d - `Merge remote-tracking branch &#39;origin/master&#39;`~~
- [x] 8c5e36f - `Update templates (#974)`
- [x] 121117c - `Update bug_fix.md`
- [x] 77c289f - `Update example_mod.md`
- [x] 09a1c32 - `Update new_feature.md`
- [x] 0dfd983 - `Fix #952`
~~6233619 - `Warning messages for 1.4 players and worlds`~~
- [x] c030352 - `Update UIWorldListItem.cs.patch`
- [x] e506ce4 - `v0.11.7.5 release, 1.4 world/player warnings, showMemoryEstimates now true`
- [x] e5749ed - `typo`
- [x] 1f64fca - `Make MessageBox texts localizable (#958)`
- [x] 9b0521b - `Grapple target point hook + aiType (#984)`
- [x] b08641d - `Fixes issue with BasicSword not clearing during Mod Creation (#992)`
- [x] 381cd10 - `Update Chinese translation (#980)`
- [x] 28684ee - `Move more hardcoded strings to resource file (#979)`
- [x] 1d0d970 - `Changed UIManagePublished offline text and changed caps on MBOfflineWithReason (#966)`
- [x] b37b6e7 - `Changed UIManagePublished offline text and changed caps on MBOfflineWithReason (#1001)`
- [x] ab2edf0 - `Fix ModTileEntities not unloading properly (#1012) Fixes #762`
- [x] 3bf06b7 - `Update CONTRIBUTING.md`
- [x] faef1a4 - `Update CODE_OF_CONDUCT.md`
- [x] cdf99d1 - `Fix minor patch mismatch in Program.cs`
- [x] 7588d7f - `Fix clientside lag when opening chests near crafting stations (don&#39;t incude the commits from this for 1.4) (#1013)`
- [x] ca58588 - `Spanish localization update (#1009)`
- [x] 6df33f8 - `readd BossHeadSlot hook, add more docs to it (#1035)`
- [x] 99c2156 - `Fix #1039`
- [x] 9d576d0 - `Update MessageBuffer.cs.patch (#1091)`
- [x] 1e34eca - `Update to previous fix to avoid corrupted data.`
- [x] b53d3bc - `Fix #953`
- [x] 0c7976f - `Fix #1041`
- [x] d38c550 - `Fix #976`
- [x] 61889b6 - `Fix #1033`
- [x] 29e61ad - `Fix #911 , no longer needed code in scripts`
- [x] 42036df - `Fix #999`
- [x] 8817b4e - `Added steam cloud quota check (#1045), Fix #1052`
- [x] d6f8d04 - `ExampleGun comments (#1036)`
- [x] 77792b8 - `Added example fishing rod (#837)`
- [x] 340ed77 - `Forgot to save.`
- [x] 563a115 - `v0.11.7.6 Beta 1 (via steam)`
- [x] 94a5cea - `Filter Mod Sources, fix ui bug, Error message for multiple Mod classes improved, fix executable bits for bin files`
- [x] 28cdfbd - `v0.11.7.6 Beta 2 via steam`
- [x] bd0f29b - `fix DrawHair not passing head, added some docs to relevant methods (#1104)`
- [x] 2cca719 - `Bandaid for #827 . Still need to track down why it doesn't work, but it won't prevent mod syncing when not desired.`
- [x] 7adb9d8 - `Partially fix #1055.`
- [x] f32445a - `Command line -publish flag`
- [x] 77a508d - `v0.11.7.6 Beta 3 via steam, fix potential disappearing xml documentation issue`
- [x] fd55615 - `Added extra temporary error logging for Mono users, why not.`
- [x] d5c4e98 - `v0.11.7.6 release`
- [x] 404eb8b - `add setupRecipes bool to detect ModRecipe misuse (#1129)`
- [x] 6d179c8 - `v0.11.7.7 Beta 1, updated hashes for 1.4.1, attempt to fix Mac Content folder`
- [x] 1e40de1 - `v0.11.7.7 Beta 2, another attempt to fix Mac Content folder`
- [x] 25a33e5 - `v0.11.7.7 release, quick ReLogic.dll protection`
- [x] 807dba7 - `Fix bug where obtaining patron sets prevents obtaining dev sets`
- [x] d291112 - `Gave KillTile an easier to understand summary (#1150)`
- [x] 87bae09 - `Fixed mis-ordering of projectile netcode (#1153)`

**Comment by Chik3r** [comment]
- [x] ecc983f - `Show tModLoader version everywhere in server menus.`
- [x] f913a7e - `Fix semicolon issue with mod generator postbuild command on linux/mac`
- [x] a246097 - `Fix #890`
- [x] 8ffbd6d - `Utils.OpenFolder, Fix #927 Fix #909 , savehere.txt fallback option`
- [x] 475faad - `Quick bandaid for #911`
- [x] 266bf53 - `v0.11.7.2 release`
- [x] 5db4c2a - `Avoid environment variable conflict`
- [x] f42c155 - `Fix content dir check for Mac`
- [x] ccdb09b - `Small fix, use ModLoader.Engine.Steam.TerrariaAppId_t`
- [x] 55996b8 - `Fix setup tool still mentioning merged source`
- [x] 03067a2 - `Refactor GoGVerifier &amp; update hashes`
- [x] 45a2baf - `Fix some mistakes in previous commit`
- [x] d0ea352 - `Turn ModRecipe into builder pattern`
- [x] 1296e29 - `Fix LogArchiver.DeleteOldArchives() not working with old logs`
- [ ] 4bc2329 - `Fix a RandomUpdate issue (Surface updates)`
- [ ] a256f9e - `Use lazy system for loading assembly references when building.`
- [ ] de821c2 - `use portable pdb writer when building mods with includePDB on Mono.`
- [x] 459cf2b - `Add null check in MdbManager.TryResolveLocation incase MdbReader.Read fails. Fixes #929`
- [ ] 615230d - `Fix #936`
- [ ] bd7aa52 - `Update ExampleLaserWeapon.cs`
- [ ] 4c6f6b6 - `Add PaintID.cs (#938) ` --- (I think this one is already in tml)
- [x] bdcd2e9 - `make MessageBoxShow overload that optionally generates tips (#871)`
- [ ] 0ef46ef - `Example Last Prism (#803)`
- [ ] b06687a - `#850`
- [x] feaa038 - `Added a menu for when world gen crashes. (#825)`
- [x] ff5a774 - `Documentation fix`
- [ ] 54cacac - `Revert changes of &quot;Turn ModRecipe into builder pattern&quot;`
- [x] da78441 - `Update UIModConfig.cs`
- [x] 56bbe30 - `Fix #934`
- [x] c55545b - `Forgot this`
- [ ] 9f62c59 - `New hashes for easier gog install`
- [x] 4b1c029 - `Steam Cloud Quota log message`
- [x] 73a7d36 - `showMemoryEstimates default to true.`
- [ ] df9b1ee - `v0.11.7.3 release`
- [ ] 8ee2966 - `v0.11.7.4 release, fix npc spawning issue from 0.11.7.3 update`
- [x] c938604 - `Updated Spanish localization (#946)`
- [x] f416f26 - `Update Terraria.Localization.Content.zh-Hans.tModLoader.json (#944)`
- [x] c9c1725 - `Restore modded banner tooltip display`
- [ ] 552d835 - `Update hashes for 1.4.0.5`
- [ ] 3029e6c - `Merge remote-tracking branch &#39;origin/master&#39;`
- [x] baa1e52 - `Fix LaunchFromSteam typo`
- [x] 7914b11 - `Update PULL_REQUEST_TEMPLATE.md`
- [x] a227d27 - `Update PULL_REQUEST_TEMPLATE.md`
- [x] 4356f94 - `Update zh-Hans.tModLoader.json (#954)`
- [x] 57de6f9 - `Fix #969`
- [ ] 1852e2d - `Merge remote-tracking branch &#39;origin/master&#39;`
- [x] 8c5e36f - `Update templates (#974)`
- [x] 121117c - `Update bug_fix.md`
- [x] 77c289f - `Update example_mod.md`
- [x] 09a1c32 - `Update new_feature.md`
- [x] 0dfd983 - `Fix #952`
- [ ] 6233619 - `Warning messages for 1.4 players and worlds`
- [ ] c030352 - `Update UIWorldListItem.cs.patch`
- [ ] e506ce4 - `v0.11.7.5 release, 1.4 world/player warnings, showMemoryEstimates now true`
- [ ] e5749ed - `typo`
- [x] 1f64fca - `Make MessageBox texts localizable (#958)`
- [x] 9b0521b - `Grapple target point hook + aiType (#984)`
- [x] b08641d - `Fixes issue with BasicSword not clearing during Mod Creation (#992)`
- [x] 381cd10 - `Update Chinese translation (#980)`
- [x] 28684ee - `Move more hardcoded strings to resource file (#979)`
- [x] 1d0d970 - `Changed UIManagePublished offline text and changed caps on MBOfflineWithReason (#966)`
- [x] b37b6e7 - `Changed UIManagePublished offline text and changed caps on MBOfflineWithReason (#1001)`
- [x] ab2edf0 - `Fix ModTileEntities not unloading properly (#1012) Fixes #762`
- [x] 3bf06b7 - `Update CONTRIBUTING.md`
- [x] faef1a4 - `Update CODE_OF_CONDUCT.md`
- [ ] cdf99d1 - `Fix minor patch mismatch in Program.cs`
- [x] 7588d7f - `Fix clientside lag when opening chests near crafting stations (don&#39;t incude the commits from this for 1.4) (#1013)`
- [x] ca58588 - `Spanish localization update (#1009)`
- [x] 6df33f8 - `readd BossHeadSlot hook, add more docs to it (#1035)`
- [x] 99c2156 - `Fix #1039`
- [ ] 9d576d0 - `Update MessageBuffer.cs.patch (#1091)`
- [ ] 1e34eca - `Update to previous fix to avoid corrupted data.`
- [x] b53d3bc - `Fix #953`
- [x] 0c7976f - `Fix #1041`
- [ ] d38c550 - `Fix #976`
- [x] 61889b6 - `Fix #1033`
- [x] 29e61ad - `Fix #911 , no longer needed code in scripts`
- [x] 42036df - `Fix #999`
- [x] 8817b4e - `Added steam cloud quota check (#1045), Fix #1052`
- [x] d6f8d04 - `ExampleGun comments (#1036)`
- [x] 77792b8 - `Added example fishing rod (#837)`
- [x] 340ed77 - `Forgot to save.`
- [x] 563a115 - `v0.11.7.6 Beta 1 (via steam)`
- [x] 94a5cea - `Filter Mod Sources, fix ui bug, Error message for multiple Mod classes improved, fix executable bits for bin files`
- [x] 28cdfbd - `v0.11.7.6 Beta 2 via steam`
- [x] bd0f29b - `fix DrawHair not passing head, added some docs to relevant methods (#1104)`
- [x] 2cca719 - `Bandaid for #827 . Still need to track down why it doesn't work, but it won't prevent mod syncing when not desired.`
- [x] 7adb9d8 - `Partially fix #1055.`
- [x] f32445a - `Command line -publish flag`
- [x] 77a508d - `v0.11.7.6 Beta 3 via steam, fix potential disappearing xml documentation issue`
- [x] fd55615 - `Added extra temporary error logging for Mono users, why not.`
- [x] d5c4e98 - `v0.11.7.6 release`
- [x] 404eb8b - `add setupRecipes bool to detect ModRecipe misuse (#1129)`
- [x] 6d179c8 - `v0.11.7.7 Beta 1, updated hashes for 1.4.1, attempt to fix Mac Content folder`
- [x] 1e40de1 - `v0.11.7.7 Beta 2, another attempt to fix Mac Content folder`
- [x] 25a33e5 - `v0.11.7.7 release, quick ReLogic.dll protection`
- [x] 807dba7 - `Fix bug where obtaining patron sets prevents obtaining dev sets`
- [x] d291112 - `Gave KillTile an easier to understand summary (#1150)`
- [ ] 87bae09 - `Fixed mis-ordering of projectile netcode (#1153)`

**Comment by Mirsario** [comment]
We're caught up. I did some commits outside this list too.
