### ISSUE TITLE
Asset Loading Post-Merge TODOs

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#1612]
Moved from #1567

> Note that async does not yet mean on demand and that the only way for an asset to be reloaded currently is switching resource packs. (Reloading mods discards all the old assets and makes a whole new AssetRepository)

**TODO:**
- [x] Change `AssetRepository.Request` to `internal` with `[InternalsVisibleTo(Terraria)]` and expose a request method for mods with the loading mode defaulting to `AsyncLoad` for consistency with `ModContent.Request`
- [x] FNA versioning in deps.json (csproj comment)
- [x] Remove obsolete methods (GetTexture/Sound, HasTexture/Sound from Mod/ModContent)
- [x] Figure out what `ResourcePackContentValidator` was ever meant to do.
  ```
  Yoraiz0r:
  It was meant to validate whole resource packs in one go, and let you know of rejections immediately
  - as right now the resource pack system only rejects on-demand and you don't know whether you have an issue until you are actually experiencing it.
  That said, this feature never made it to fruition, and most of what you see in the compiled code is just a dummy state.. that is unused, too.
  So you can feel free to remove/ignore it.
  ```
- [ ] Check all ExampleMod calls to `ModContent.Request` to make sure the loading mode is appropriate
- [ ] Let mods add to the asset reader pool.
- [ ] Allow resource packs to affect mod assets.
  - [ ] Wrap the content source list with delegating sources that prepend the mod name to the path.
  - [ ] Mod content validators; Auto-build a texture size chart.
- [ ] Allow mods to add resource packs for overriding vanilla assets.
  - [ ] A default one, if a mod contains a `Terraria/` directory.
  - [ ] Additional custom ones via code, can be enabled and disabled.
- [ ] Make better use of async asset loading.
  - [ ] Use the content validator to produce placeholder textures with appropriate size.
- [ ] Log rejections (and give content sources a decent `ToString()`.)
- [ ] Test performance impact (on load time) of opening new file streams for every TmodFile asset request.
- [ ] Don't constantly request glow textures.
- [ ] Test if mod building works in headless environments (don't know why it wouldn't.)
- [ ] Make Asset\<Texture2D\>.Value return dummy transparent textures until asynchronous loading finishes.

**Comment by RighteousRyan1** [comment]
Resource packs that add/replace sounds cause issues on texture pack load. Causes the UI to bug out and in the end- results in a softlock.
